### ISSUE TITLE
Remove MagicalRecord dependency

### ISSUE THREAD

**Issue by jonathanpenn** [alloy/MotionData#2]
Creating this issue from an email conversation Eloy and I had. Here's the summary of my reasoning:

I love what Saul has done with the MagicalRecord project for simplifying the Objective C idioms, but it seems kinda heavy to include that whole library. And with the idea of having MotionData's own namespace for CoreData sublcasses, we could reimagine how MagicalRecord's functionality could work without using categories to bolt methods onto CoreData objects directly.

I already have a plan to start pulling this out unless I hear any objections.

**Comment by alloy** [comment]
The dependency is gone. We still need to port things, though, like actually creating a SQLite disk store etc.
