### ISSUE TITLE
Example app raising an exception...

### ISSUE THREAD

**Issue by Bodacious** [alloy/MotionData#4]
hey - I really like the look of MotionData - I'm having trouble getting it to work though. I get the same error when loading it into my app or running the example Recipes app:

```
uninitialized constant MotionData::MotionDataManagedObjectBase (NameError)
*** Terminating app due to uncaught exception 'NameError', reason: 'uninitialized constant MotionData::MotionDataManagedObjectBase (NameError)
```

Can you please explain how I can get the basics up and running in a standalone app? Thanks

**Comment by jonathanpenn** [comment]
Take a look at this commit https://github.com/alloy/MotionData/commit/ef370971279e868f87cc012205c9fd62597864e7, and you'll see what to do.

Apparently, in all the shuffle going on, the Recipies example broke for two reasons.
1. Two new ruby files were created (predicate.rb and scope.rb) when those parts were extracted out but they weren't added to the Rakefile manifest for the example.
2. Eloy needed to drop down to Objective C to do some swizzling magic to get things to work and those files were referenced in the `ext` directory in the root of the project. I needed to add that reference to the Rakefile in the Recipies example, too.

The app builds fine for me now. I'm going to go ahead and mark this as closed. Feel free to reopen it with more info if it's still not working for you, or leave further comments if you want clarification.
